### PR TITLE
Delayed job checker

### LINKED ISSUE #43: Check whether delayed_job is running and alert user if it is not
Let them know that without it, e-mails will not go out.

### LINKED ISSUE #52: 'Last Updated' value in 'About dialog' is broken
See RM for current solution.

### PR DESCRIPTION
**Pull request by retypepassword**
Checks whether or not delayed job is running and displays a notification on the message index page if not. Fixes #43. Also fixes #52 (changes the last updated value to N/A).

### CODE REVIEW

File: app/controllers/delayed_job_status_controller.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  def index
+    @status = DelayedJobWorker.status
+
+    case @status
+    when 0b00
+      render :text => "Yes", :status => :ok
+    when 0b01, 0b10
+      render :text => "Maybe", :status => :ok
+    else
+      render :nothing => true, :status => :"i'm_a_teapot"
```
Comment (okadri) [inline app/controllers/delayed_job_status_controller.rb]: Haha.. cool status code. never heard of it before!

**Comment by okadri** [comment]
+1
